# Generated by Django 3.2.3 on 2021-05-23 04:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='headline',
            field=models.CharField(default='Default headline', max_length=120, verbose_name='Headline'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modified At'),
        ),
    ]
