# Generated by Django 3.2.3 on 2021-05-24 23:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210523_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='about',
            field=ckeditor.fields.RichTextField(verbose_name='About Me'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Job Description'),
        ),
    ]
