# Generated by Django 3.2.3 on 2021-05-26 02:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210524_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Course description'),
        ),
    ]
