# Generated by Django 3.2.3 on 2021-06-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='skills',
            name='tag',
            field=models.ManyToManyField(related_name='tag', to='pages.SkillsTag'),
        ),
    ]
