# Generated by Django 3.2.4 on 2021-06-12 22:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210601_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='problem',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='The Problem'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='solution',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='The Solution'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tag',
            field=models.ManyToManyField(related_name='skilltags', to='pages.SkillsTag'),
        ),
        migrations.AlterField(
            model_name='education',
            name='course',
            field=models.CharField(max_length=100, verbose_name='Degree/Certificate'),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Course description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='About Me'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='pages.SkillsTag'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work', to='pages.resume'),
        ),
        migrations.CreateModel(
            name='PortfolioImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('alt', models.CharField(max_length=50, verbose_name='Alt Description')),
                ('portfolio_image', models.ImageField(upload_to='portfolio_pics/')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.portfolio')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField(verbose_name='Feature')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pages.portfolio')),
            ],
        ),
    ]
