# Generated by Django 3.2.3 on 2021-06-12 23:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210612_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Portfolio Description'),
            preserve_default=False,
        ),
    ]
