# Generated by Django 3.2.3 on 2021-10-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_workexperience_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='repo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Repository Url'),
        ),
    ]
