# Generated by Django 3.2.3 on 2021-10-07 20:47

from django.db import migrations, models


def reorder(apps, schema_editor):
    my_model = apps.get_model("config", "Portfolio")
    order = 0
    for item in my_model.objects.all():
        order += 1
        item.my_order = order
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20211007_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['view_order']},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='view_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(reorder),
    ]
